spring:
  datasource:
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/spring_boot?useTimezone=true&serverTimezone=UTC
      username: root
      password: conta@8122